### ISSUE TITLE
File input glob notation

### ISSUE THREAD

**Issue by gageorsburn** [log-store/log-ship#3]
It would be helpful if the file path took a glob pattern so we could specify multiple files e.g. `/var/log/containers/*.log`. When deploying log ship in a K8s environment, we won't know the file paths ahead of time since the file names are based off of the container name which is dynamic.

**Comment by log-store** [comment]
@gageorsburn, thanks for the feature request!

Please see 4757eb2. It *should* address your request. A new version of log-ship will be built with a few other changes, and released as v1.2.0.

**Comment by gageorsburn** [comment]
@log-store Thanks for doing this!

One problem is this though:
> File globbing **only** occurs once, so newly added files will not automatically be "picked up" by this plugin.

With Kubernetes being a dynamic environment new files will come and go due to the nature of things. The way this all works is a pod in Kubernetes is the smallest unit of deployable compute. Pods can be scheduled to nodes based on their scheduling constraints (you can get pretty advanced with how you want to schedule pods onto nodes) but from a logging perspective pods are coming and going all the time and getting scheduled to different hosts. How the logging works is we end up having the container runtime on each host (docker, containerd etc) dump stdout from containers to a file per container`/var/log/containers/<container_name>.log`. We run log-ship as a daemonset so that it gets scheduled on every node. The log-ship pod ends up mounting the `/var/log` directory from the host. The issue with the with the above is that a new pod could get scheduled on the node and it's logs for the new pod won't get sent until the log-ship pod is restarted.
